# Basic config for Basic plugin

chat:
  player-join-message: "&7&l[&2&l+&7&l] &7{player}"
  player-quit-message: "&7&l[&4&l-&7&l] &7{player}"

  message-format: "&f&l{player}&r&f: {message}"

modules:
  combat-tag:
    enabled: false
    combat-tag-time: 20
  combat-optimizations:
    disable-knockback-resistance: false
    enable-snowball-knochback: false
    attack-speed: 4.0
    no-damage-ticks: 10
  inventory-saver:
    percentage-of-keep-inventory: 0